name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:

    name: Tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby-version: ['2.3', '2.4', '2.5', '2.6', '2.7', '3.0', 'jruby-9.2.9.0']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: false

    - name: Install native dependencies for Ruby 3.0
      if: ${{ startsWith(matrix.ruby-version, '3.') }}
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev

    - name: Configure bundler
      if: ${{ startsWith(matrix.ruby-version, '3.') }}
      run: |
        bundle config set --local force_ruby_platform true
        bundle install

    - name: Install dependencies for other Ruby versions
      if: ${{ !startsWith(matrix.ruby-version, '3.') }}
      run: bundle install

    - name: Run tests
      run: bundle exec rake